config/routes.rb
Rails.application.routes.draw do
  resources :entries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    # def localtime(utc_offset = nil)
    #   utc = new_offset(0)
    #
    #   Time.utc(
    #     utc.year, utc.month, utc.day,
    #     utc.hour, utc.min, utc.sec + utc.sec_fraction
    #   ).getlocal(utc_offset)
    # end
    alias_method :getlocal, :localtime

    if @entry.save
      redirect_to entries_path
    else
      raise "Cannot Save!"
    end
  end

  def new
  end

  def edit
    @entry = Entry.find(params[:id])
  end


  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to entries_path
    else
      render :edit
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:author, :photo_url, :date_taken)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div class="container">
  <h3>Posted by: <%= entry.author %> on <%= entry.date_taken %></h3>
  <img class="image-upload" src="<%= entry.photo_url %>"/>
  <div class="edit">
    <p><%= link_to image_tag("Cleaver.png", height: '110', width: '100'), edit_entry_path(entry.id)%>           <%= link_to image_tag("destroy.png", height: '100', width: '75'), entry_path(entry.id), method: :delete %></p>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <%= f.label :author %>: <%= f.text_field :author %> <%= f.label :photo_url %>: <%= f.text_field :photo_url %> <%= f.label :date_taken %>: <%= f.text_field :date_taken %> <%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Item</h1>
<%= render 'entry', entry: @entry %>
<%= render 'form', entry: @entry %>

app/views/entries/index.html.erb
<div class="container header">
  <h1>GWARstagRAM!!!</h1>
</div>
<div class="container form">
  <h3>Create New Sacrifice</h3>
  <%= render 'form', entry: @entry %>
</div>
<div id="entires-list" class="containter">
  <% @entries.each do |entry| %>
    <%= render partial: 'entry', object: entry %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WdiInstagram</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Creepster" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>